# Generated by Django 5.1.1 on 2024-10-01 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_parentproduct_title_addtocart_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='child_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_to_cart_product', to='catalog.childproduct'),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_to_cart_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
